---
title: |
  | HCS7004 - Lab 3:
  | Software installation and containers
pagetitle: "HCS7004 - Lab 3"
output:
  html_document:
    number_sections: true
    highlight: tango
    toc: true
    toc_float: true
---

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy()
```

<br/>

******
<br/>

To get started, we'll create and move into a directory for this lab: 
```{bash, eval=FALSE}
hcs7004@ubuntu:~$ mkdir lab3_containers
hcs7004@ubuntu:~$ cd lab3_containers
```

<br/>

# The `$PATH` environment variable

The `$PATH` environment variables holds all the directories from which executables can be called directly, that is, without specifying the full path to the executable. Let's see which directories are in our `$PATH`.
```{bash, eval=FALSE}
hcs7004@ubuntu:~$ echo $PATH                          # The output is a little hard to read...

hcs7004@ubuntu:~$ echo $PATH | tr ":" "\n" | nl       # That's better!
```

<br/>

Do you remember how we can add a directory to `$PATH`? Let's say we want to add our newly created dir `lab3_containers`.

<details>
<summary>Show answer</summary>
```{bash, eval=FALSE}
hcs7004@ubuntu:~$ PATH=$PATH:$HOME/lab3_containers/
```
Here, I used `$HOME` instead of `/home/<my-user-name>`, because it will work for any of you regardless of your user name. `$HOME` is another environment variable; as is your user name `$USER` -- so we could have also entered `/home/$USER` regardless of the actual user name.
</details>
<br/>

To permanently add a directory to `$PATH`, add it to your `~/.bashrc` file.
How could we do this in a single line on the command line?

<details>
<summary>Show answer</summary>
```{bash, eval=FALSE}
hcs7004@ubuntu:~$ echo "PATH=$PATH:$HOME/lab3_containers/" >> ~/.bashrc
```
</details>
<br/>

With the `which` command (or `whereis` for similar results), we can check where software that is available to the `$PATH` is located, since we can have many directories in it. Even commands like `grep` have executables, and they can simply be called by their name because these executables are in dirs in your `$PATH`:
```{bash, eval=FALSE}
hcs7004@ubuntu:~$ which grep
```

******
<br/>

# Use of `apt-get`

For software installation on an Ubuntu operating system, such as the one in your virtual box, `apt-get` is your go-to command. When you install software (“packages”) this way, the software will be available in your `$PATH`, dependencies will be automatically handled, and you will be prompted whenever software updates become available to the package manager.

Recall that we'll need admin privileges to use `apt-get`, and will therefore prepend our commands with `sudo`. This way, we execute the commands with admin rights/privileges (“`sudo` privileges”). When you execute the first command with `sudo` below, you’ll be prompted for your personal password (and whenever you use `sudo` again within the next 15 minutes, you won’t be prompted).

Some bioinformatics tools, such as `samtools`, are available through `apt-get`:
```{bash, eval=FALSE}
hcs7004@ubuntu:~$ samtools                        # This should not work: samtools is not installed

hcs7004@ubuntu:~$ apt-get update                  # Nope!

hcs7004@ubuntu:~$ sudo apt-get update             # First, update the package manager index
hcs7004@ubuntu:~$ sudo apt-get install samtools   # Then install samtools (answer "Y" when prompted)

hcs7004@ubuntu:~$ samtools                        # Now, samtools is installed & available in $PATH
```
<br/>

Today, we will be working with the container software **`Singularity`**, which is *not* available through `apt-get`. Therefore, we will first need to install its dependencies, some with `apt-get` and others manually, and *then* we install Singularity manually.

We start with installing a few of the Singularity dependencies with `apt-get`.
```{bash, eval=FALSE}
hcs7004@ubuntu:~$ sudo apt-get install -y build-essential libssl-dev uuid-dev wget
```

******
<br/>

# Installing `Singularity`
Since the installation of Singularity involves relatively many steps, we’ll use the shell script `installing_singularity.sh`. Like any shell script, it is simply a collection of shell commands. In other words, you could also enter these commands one-by-one on the command line. These commands were taken from the [Singularity installation instructions](https://sylabs.io/guides/3.5/user-guide/quick_start.html#quick-installation-steps), so there is no magic here.

<br/>

We download the script with installation instructions:
```{bash, eval=FALSE}
hcs7004@ubuntu:~$ mkdir $HOME/lab3_containers/singularity_install
hcs7004@ubuntu:~$ cd $HOME/lab3_containers/singularity_install

hcs7004@ubuntu:~$ wget http://bit.ly/HCS7004 -O installing_singularity.sh
hcs7004@ubuntu:~$ ls

hcs7004@ubuntu:~$ chmod u+x installing_singularity.sh     # This will make the script executable
hcs7004@ubuntu:~$ ls                                      # Note the change in color!
```
<br/>

Have a look at the script to get an idea of what's being done there. How do we do that again?

<details>
<summary>Show answer</summary>
```{bash, eval=FALSE}
hcs7004@ubuntu:~$ less installing_singularity.sh

hcs7004@ubuntu:~$ head installing_singularity.sh        # We could also take a look at the first few lines
hcs7004@ubuntu:~$ cat installing_singularity.sh         # Or print the entire file to the screen (not always ideal)
```
</details>
<br/>


- What do you think the first line of the script does?
- Please identify at least one line in the script that you would like to understand better. 

<br/>

Now, we’ll run the script:
```{bash, eval=FALSE}
hcs7004@ubuntu:~$ ./installing_singularity.sh
```

<br/>

Let’s check whether `Singularity` was successfully installed:
```{bash, eval=FALSE}
hcs7004@ubuntu:~$ cd $HOME/lab3_containers
hcs7004@ubuntu:~$ singularity
```

******
<br/>

# Our options to run `multiqc`
`multiqc` is an extremely useful program for summarizing quality control (“QC”) results for multiple samples. Unfortunately, it’s not available at OSC. (How could we check this?)

<br/>

Now, our main options are:

1. Install it manually
2. Use `conda`
3. Use a container

What are some pros and cons of these different options?

<br/>

We'll now look for `multiqc` at the [Biocontainers website](https://biocontainers.pro). Click on “*Registry*” in the top bar, then enter “*multiqc*” in the search box. Do you get any hits?

The [tool page](https://biocontainers.pro/#/tools/multiqc) that you should have found gives lots of details, including installation instructions with `conda`, `Docker`, and `Singularity`. It's perhaps a bit confusing that this website also gives `conda` options, since that's not technically a container platform, but it's still handy.

******
<br/>

# Downloading and running a `multiqc` container

At [multiqc's Biocontainers page](https://biocontainers.pro/#/tools/multiqc), we find the following instructions for Singularity, which will download and run the container:
`singularity run https://depot.galaxyproject.org/singularity/multiqc:1.9--pyh9f0ad1d_0`.

Another registry that hosts all Biocontainers is [quay.io](https://quay.io/), which provides the shorter, canonical notation
for downloading the container, so we'll use that one below.
Additionally, we'll use separate commands to download and run the container, so that we get the image file in our working directory:

```{bash, eval=FALSE}
hcs7004@ubuntu:~$ singularity pull docker://quay.io/biocontainers/multiqc:1.9--py_1

hcs7004@ubuntu:~$ singularity run multiqc_1.9--py_1.sif
Singularity>
```

Apparently, the default run script was to enter a shell (i.e. a terminal) within the container, as indicated with the `Singularity>` prompt. You should also see this prompt yourself, and it indicates that your are inside the container.

<br/>

How could we check whether `multiqc` is installed?

<details>
<summary>Show answer</summary>
```{bash, eval=FALSE}
Singularity> multiqc

Singularity> multiqc --help       # Commonly available option for a lot of software

Singularity> multiqc --version    # Idem
```
</details>
<br/>

Which version of `multiqc` did we just download?
Which other versions are available, and how would we download one of those?

******
<br/>

# Building our own container

To practice, we’ll now build our own `Singularity` container with `multiqc.` Recall that you need `sudo` privileges to build a container, so we'll do this on our own computer/Virtualbox.

<br/>

First, create a directory for the container (within the dir):
```{bash, eval=FALSE}
hcs7004@ubuntu:~$ mkdir multiqc       # Full path should be $HOME/lab3_containers/multiqc
```
<br/>

We will now create a special type of container image that allows for interactive modification using the `--sandbox` option, with `multiqc/` being the target directory (which will be created) and `docker://ubuntu:20.04` being the base image.

```{bash, eval=FALSE}
hcs7004@ubuntu:~$ sudo singularity build --sandbox multiqc/ docker://ubuntu:20.04
```

Once the build is complete, we have created a container with an Ubuntu OS, and can simply open a shell in it with the `singularity shell` sub-command. How did this compare to installing an Ubuntu Virtual Machine?

<br/>

Now, when we ussue the `singularity shell` command, we will also use the `--writable` option: that way, the container image will be modified by what you do in the container (as opposed to regular usage of a container, in which it is used as a *static* computing environment):

```{bash, eval=FALSE}
hcs7004@ubuntu:~$ sudo singularity shell --writable multiqc/
```
(You’ll get a few warnings, which can be ignored.)
<br/>
<br/>

Now, we have entered the container: the commands below should be entered inside the container, as again indicated by the `Singularity>` prompt. We’ll first update the package manager index and install two dependencies for `multiqc.` Note that we don’t need `sudo` for the `apt-get` commands: because we entered the container with `sudo` privileges, those *carried over* into the container.

```{bash, eval=FALSE}
Singularity> apt-get update
Singularity> apt-get install -y python3-pip git     # This will take a while
```
<br/>

Now, we’ll install `multiqc` using the Python package manager `pip` (which we just installed above):
```{bash, eval=FALSE}
Singularity> pip3 install git+https://github.com/ewels/MultiQC.git
```
<br/>

Let’s test whether that worked:
```{bash, eval=FALSE}
Singularity> multiqc -h
Singularity> multiqc --version
```
<br/>

We’ll exit the container:
```{bash, eval=FALSE}
Singularity> exit
```
<br/>

Now, from our special sandbox container, we’ll build a regular container image file. We’ll later transfer this image file to OSC to run `multiqc` there. (We could also upload our image to a personal, public repository so that others can use our container, too.)

Note that we use the `build` sub-command again, but now without the `--sandbox` option. As arguments, we give the target image file `multiqc.sif` (with `.sif` being the standard extension for `Singularity` container image files) and the existing sandbox directory `multiqc/`:
```{bash, eval=FALSE}
hcs7004@ubuntu:~$ sudo singularity build multiqc.sif multiqc/
```
<br/>

Excellent, we have created a container image!

******
<br/>

# Running our container at OSC

We’ll upload our container image to OSC using `sftp`:

```{bash, eval=FALSE}
hcs7004@ubuntu:~$ sftp <username>@sftp.osc.edu  # Replace "<username>" by your actual OSC user name

sftp> mkdir /fs/scratch/PAS1752/<username>/lab3_containers/ # Note: we can use regular shell commands
sftp> put multiqc.sif /fs/scratch/PAS1752/<username>/lab3_containers/
sftp> exit
```
<br/>

Now, let’s move to OSC. You can either `ssh` in (`ssh <username>@owens.osc.edu`), or open a terminal in [OnDemand](http://ondemand.osc.edu/). Then, go the directory that you uploaded the container image file to:
```{bash, eval=FALSE}
[<user>@owens-login01 ~]$ cd /fs/scratch/PAS1752/$USER/lab3_containers/
[<user>@owens-login01 ~]$ ls # You should see you container "multiqc.sif"
```
<br/>

`Singularity` is installed at OSC, but it does need to be loaded first:
```{bash, eval=FALSE}
[<user>@owens-login01 ~]$ module load singularity
```
<br/>

Now, we’ll run `multiqc` from our container. We do this using another `singularity` sub-command: `exec` (short for “*execute*”).
```{bash, eval=FALSE}
[<user>@owens-login01 ~]$ singularity exec multiqc.sif multiqc -h
[<user>@owens-login01 ~]$ singularity exec multiqc.sif multiqc --version
```
<br/>

With `singularity exec`, we executed a shell command inside the container and immediately exited. Recall that running software this way is almost the same as running locally installed software:

```{bash, eval=FALSE}
$ multiqc -h                        # This is what you would do if you had multiqc installed locally

$ singularity exec multiqc.sif \    # “Containerized” execution.
     multiqc -h                     
```

******
<br/>

# File sharing with containers

So far, all we did with `multiqc` was run its help function. What if we wanted it to analyze actual data have output returned by the program -- how would that work with a container?

An important aspect of dealing with containers is the sharing of files between host and container. With Singularity (but not Docker), several directories are "*bind-mounted*" (attached/connected) between the host and container *by default*:

- `$HOME` (`/home/$USER`): your home directory
- `$PWD`: your current working directory
- `/tmp`
<br/>

Moreover, when you enter a container (e.g. via `singularity shell`) or execute a command directly (via `singularity exec`), you will be located at your host's current working directory within the container, too. And since the current working directory is bind-mounted by default, this means that files written to the current directory in the container, will also be (and remain) present in the host.

Confusing? Let's look at this in practice:
```{bash, eval=FALSE}
[<user>@owens-login01 ~]$ pwd         # Let's check our current dir at OSC (the host)
[<user>@owens-login01 ~]$ ls          # And let's list our files there

[<user>@owens-login01 ~]$ singularity shell multiqc.sif # Enter the container
Singularity> pwd                      # Where are we inside the container?
Singularity> ls                       # And which files do we see?
Singularity> touch ThisFileWasCreatedInsideTheContainer # Create a new file inside the container
Singularity> exit

[<user>@owens-login01 ~]$ ls          # Do you see the file you created inside the container?
```
<br/>

At OSC, the following directories are also bind-mounted by default:

- `/fs/project`
- `/fs/scratch`

<br/>

Finally, we can bind-mount directories upon runtime of the container,
using the `-B` option: `singularity exec -B dir/in/host[:/dir/in/container] <image.sif>`.
By default, the path in the container will be the same as in the host, but this can be changed by appending `:/dir/in/container`.


******
<br/>


# *Really* running our container

Start by making sure you have the `singularity` module loaded and are in the right directory:

```{bash, eval=FALSE}
[<user>@owens-login01 ~]$ module load singularity
[<user>@owens-login01 ~]$ cd /fs/scratch/PAS1752/jelmer/lab3_containers/    # Or your own dir if you copied the .sif file
[<user>@owens-login01 ~]$ ls                                                # You should see "multiqc.sif"
```

<br/>

Now we are ready to run `multiqc` with some actual data. What `multiqc` does is summarize individual-level QC results from other programs such as `fastqc`. Therefore, its input can be a number of `fastqc` output files. I have put some of those in `/fs/ess/PAS1752/HCS7004_Files/Lab3/fastqc_files`. Let's see:

```{bash, eval=FALSE}
[<user>@owens-login01 ~]$ ls /fs/ess/PAS1752/HCS7004_Files/Lab3/fastqc_files
```
<br/>

Since `/fs/ess/` happens *not* to be bind-mounted by default, we will need to do this manually. Otherwise, to run `multiqc`, all we need to do is specify the directory with files to analyze:

```{bash, eval=FALSE}
[<user>@owens-login01 ~]$ fastqc_dir=/fs/ess/PAS1752/HCS7004_Files/Lab3/fastqc_files
[<user>@owens-login01 ~]$ singularity exec -B $fastqc_dir multiqc.sif multiqc $fastqc_dir
[<user>@owens-login01 ~]$ ls
```

Why did we create a variable `$fastqc_dir` first?

<br/>

Now we have performed an actual analysis using a container!

******
<br/>

# Appx. 1: More `module`

Logged in at OSC, we'll try some `module` commands for loading and unloading software.

First, let's explore the modules (software) that are available.

- `module avail` will list all the modules that can be directly loaded, given the current environment.
- `module spider` will list all modules that could potentially be loaded, and you can also add a search term to narrow down the results.

Let's compare:

```{bash, eval=FALSE}
[<user>@owens-login01 ~]$ module avail        # Look around; and check which versions of R you see

[<user>@owens-login01 ~]$ module spider       # Idem as above

[<user>@owens-login01 ~]$ module spider R     # Narrow down to R immediately
```

Were the available versions of R different between the `module avail` and `module spider` commands? 

<br/>

Now, let's load `R` without specifying a version:

```{bash, eval=FALSE}
[<user>@owens-login01 ~]$ module load R
```

Which version of `R` was loaded?

<br/>

But we heard lots of good things about the latest version of R, so we'll load that instead:
```{bash, eval=FALSE}
[<user>@owens-login01 ~]$ module unload R             # First unload the default R version
[<user>@owens-login01 ~]$ module load R/4.0.2-gnu9.1  
```

What happened when we did this, besides the switch of the `R` version?


******
<br/>

# Appx. 2: Using `conda` at OSC

Let's create a `conda` environment with `multiqc` installed.

<br/>

First, we need to load the appropriate module at OSC: 
```{bash, eval=FALSE}
[<user>@owens-login01 ~]$ module load python/3.6-conda5.2 # (conda is associated with Python)
```
<br/>

While we could now install `multiqc` directly, best practice is to maintain a separate environment for each piece of software (why?). Therefore, we will all at once create a new `conda` environment (that we will simply name `multiqc`) and install `multiqc` in it:
```{bash, eval=FALSE}
[<user>@owens-login01 ~]$ conda create -y -n multiqc -c bioconda multiqc # This will take a while
```

- `create` is the `conda` sub-command to create a new environment.
- `-y` avoids a confirmation prompt.
- `-n multiqc` is the name for the new environment.
- `-c bioconda` is the `conda` "channel" we download from.
- `multiqc` is the name of the package.

If `conda` complains, saying that your shell is not configured properly for `conda`, you need to run the following (as that long error message should also specify):
```{bash, eval=FALSE}
[<user>@owens-login01 ~]$ echo ". /usr/local/python/3.6-conda5.2/etc/profile.d/conda.sh" >> ~/.bashrc
```
This will run a `conda` setup shell script whenever you open a terminal (since `~/.bashrc` is always run when you open a terminal).

<br/>

Now, we activate the `multiqc` environment and see if we can run it: 
```{bash, eval=FALSE}
[<user>@owens-login01 ~]$ conda activate multiqc
(multiqc) [<user>@owens-login01 ~]$ multiqc --help    # The prompt shows your conda environment!
```

******
<br/>

# Appx. 3: Writing a Singularity *Definition file*

It is best practice to produce your *final* container image from a text file
containing the recipe for the build,
namely a *Definition file* when creating a `Singularity` image,
or a *Dockerfile* when creating a `Docker` image.
While it is fine to initially build things interactively like we did in Section 6, once
that is done, the next step is to write a recipe file.
Understanding these files will also help you when you find a container image (and its recipe file)
that is similar to what you want but not exactly right, so you can quickly edit it.

<br/>

Now, we'll create `Singularity` *Definition file* (*Def file* for short) for the container
that we built interactively in Section 6.
Let's start by creating and moving into a new directory, and then creating and opening
a text file that will become our *Def file*.

```{bash, eval=FALSE}
hcs7004@ubuntu:~$ mkdir def-file-build
hcs7004@ubuntu:~$ cd def-file-build

hcs7004@ubuntu:~$ nano multiqc_mini.def
```

<br/>

To get started with the *Def file*, we'll define the starting image (base layer) --
like in Section 6, we'll use the latest stable Ubuntu release.
In *Def files*, we start with a *Header* that uses keywords to define the base operating system,
with `Bootstrap:` indicating the registry and `From:` the base image.
So, our `docker://ubuntu:20.04` label in the interactive build becomes:

```{bash, eval=FALSE}
Bootstrap: docker             # Enter these definition file lines in Nano!
From: ubuntu:20.04 
```

<br/>

The main content is broken up into optional predefined sections indicated with `%<section-name>`.
The `%post` section is generally the most important;
here, we can for example enter shell commands that perform software installation.

```{bash, eval=FALSE}
%post                         # (We're still in Nano!)
    apt-get update            # Indent these lines with a tab
    apt-get install -y python3-pip git
    pip3 install git+https://github.com/ewels/MultiQC.git
```

It is important to add the `-y` option to `apt-get install` in this case,
since building the container happens non-interactively and we wouldn't be able to answer a prompt. 

<br/>

From these few lines, we can already build a container!
Save your changes in `nano` by pressing `Ctrl + O` (and `Enter` to confirm), and then exit by pressing `Ctrl + X`. 
We'll use the `build` sub-command to build a container image from our *Def file*:

```{bash, eval=FALSE}
hcs7004@ubuntu:~$ sudo singularity build multiqc_mini.sif multiqc_mini.def
```

<br/>

We've built a container from scratch!
Finally, let's test it:

```{bash, eval=FALSE}
hcs7004@ubuntu:~$ singularity exec multiqc_mini.sif multiqc --version
```

******
<br/>

# Appx. 4: Improving our *Def file*

We'll now make a number of small improvements to our *Def file*, mostly in "best practice" fashion.

Copy the initial *Def file* to a new file and open it in `Nano`:

```{bash, eval=FALSE}
hcs7004@ubuntu:~$ cp multiqc_mini.def multiqc_improved.def
hcs7004@ubuntu:~$ nano multiqc_improved.def
```

First, we'll add two lines to our `%post` section, to clean up after installation,
which may reduce the size of the resulting container image.

```{bash, eval=FALSE}
%post
    apt-get update
    apt-get install -y python3-pip git
    apt-get clean all                   # Add this line
    apt-get purge -y                    # Add this line
    pip3 install git+https://github.com/ewels/MultiQC.git
```

<br/>

Next, we'll add some metadata, so that other people who may get a hold of our container image file
(for instance, after we share our image at a registry),
will know what it does and who produced it.
For this, we use the `%labels` section with a couple of keyword-value combinations,
and the `%help` section with free-form text describing the container:

```{bash, eval=FALSE}
%labels
    Author HCS7006
    Version latest
    
%help
    This container has MultiQC installed on top of ubuntu 20.04
```

<br/>

Finally, we will add a default command that will be executed if we would run the
resulting image with the `singularity run` sub-command.
`multiqc --version` could be a useful command here:

```{bash, eval=FALSE}
%runscript
    multiqc --version
```

<br/>

Exit `nano` (`Ctrl + O` then `Ctrl + X`) and build and run the improved container image:

```{bash, eval=FALSE}
hcs7004@ubuntu:~$ sudo singularity build multiqc_improved.sif multiqc_improved.def

hcs7004@ubuntu:~$ singularity run multiqc_improved.sif
```

<br/>

A useful section that we haven't used is `%files`,
which can be used to copy files into the container.
The [Singularity documentation on Def files](https://sylabs.io/guides/3.0/user-guide/definition_files.html)
has information on these and even more possible sections.

******
<br/>

# Appx. 5: Assigning variables

In the section on `$PATH`, we saw a bit of variable assignment at the command line, but perhaps this did not become entirely clear.
Let's look at it a bit more to clarify:

```{bash, eval=FALSE}
hcs7004@ubuntu:~$ echo "My latest masterpiece" > book.txt   # First we create a mock file

hcs7004@ubuntu:~$ recommended_book="book.txt"               # Assign using variable=value / variable = "value"

hcs7004@ubuntu:~$ echo $recommended_book                    # Recall the variable using a "$"
hcs7004@ubuntu:~$ cat $recommended_book                     # This works too - it will display the file contents!
```

******
<br/>

# Appx. 6: Manual installation

<br/>

## Install `vcftools` manually
```{bash, eval=FALSE}
wget https://github.com/vcftools/vcftools/tarball/master -O vcftools.tar # Download the archive
tar -xvf vcftools.tar               # Unpack the archive
cd vcftools-vcftools-581c231/       # Move into the dir that was created
./autogen.sh                        # Run a script that will generate the configure script
./configure                         # Run the configure script
make                                # Compile the program
sudo make install                   # Optional - copy the executables to your $PATH

cd ..                               # Move out of the vcftools dir
vcftools                            # Check if it's installed
```

<br/>

## Install `bowtie2` manually
```{bash, eval=FALSE}
git clone https://github.com/BenLangmead/bowtie2.git # Download using the git's clone sub-command
cd bowtie2                          # Move into the dir
make                                # Compile the program
sudo make install                   # Optional - copy the executables to your $PATH

cd ..                               # Move out of the bowtie dir
bowtie2                             # Check if it's installed
```
